// Central event details for The Nanit Reset — reused across modules so wording stays consistent.
export const EVENT = {
  name: 'The Nanit Reset',
  dateLong: 'Monday, 16 November 2026',
  dateShort: '16 November 2026',
  dayDate: 'Monday 16 November',
  time: '11:00am – 2:00pm',
  doorsOpen: '10:30am',
  rsvpBy: 'Wednesday 4 November',
  venue: 'The Atrium, The Grounds of Alexandria',
  address: '7a / 2 Huntley Street, Alexandria NSW 2015',
  location: 'The Atrium, The Grounds of Alexandria, 7a / 2 Huntley Street, Alexandria NSW 2015',
  city: 'Sydney',
  organiser: 'Coolkidz Australia',
  brand: 'Nanit',
  signerName: 'Melanie Kingsford',
  signerRole: 'Coolkidz Australia',
  contactEmail: 'hello@coolkidz.com.au',
  attendees: '~30 guests',
}
